### ISSUE TITLE
reference to a non existing file

### ISSUE THREAD

**Issue by dadtmt** [arnauddchamps/project-artezic#13]
`<link rel="stylesheet" media="screen and (max-width: 540px)" href="petite_resolution.css" />`

**Comment by arnauddchamps** [comment]
https://github.com/arnauddchamps/project-artezic/commit/643623d00e2bb5fa6df0c82974d7e6acf98d00a5

**Comment by arnauddchamps** [comment]
issue#13

**Comment by arnauddchamps** [comment]
https://github.com/arnauddchamps/project-artezic/pull/22/files
